import './globals.module.scss';
import { Inter } from 'next/font/google';

export const metadata = {
  title: { default: 'Amaphones', template: '%s | Amaphones' },
  description: 'Generated by create next app',
};

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1>{children}</h1>
        <span>About</span>
        <br />
        <span>Contacts</span>
      </body>
    </html>
  );
}
