import { Inter } from 'next/font/google';
import styles from './globals.scss';

export const metadata = {
  title: { default: 'Hi-Fi Harmony', template: '%s | Hi-Fi Harmony' },
  description: 'Generated by create next app',
};

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <nav>
            <div className="menu">
              <form action="/#">
                <button className="btn-25">Hi-Fi Harmony</button>
              </form>
              <form form action="/earbuds">
                <button className="btn-25">Earbuds</button>
              </form>
              <form action="/headphones" method="get">
                <button className="btn-25">Headphones</button>
              </form>
              <form action="/basket" method="get">
                <button className="btn-24">Basket(5)</button>
              </form>
            </div>
          </nav>
        </header>

        <section>{children}</section>
      </body>
    </html>
  );
}
