import { Inter } from 'next/font/google';
import Badge from './componenets/Badge';
import CookieBanner from './CookieBanner';
import styles from './globals.scss';

export const metadata = {
  title: { default: 'Hi-Fi Harmony', template: '%s | Hi-Fi Harmony' },
  description: 'Generated by create next app',
};

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <nav>
            <div className="menu">
              <form action="/">
                <button className="btn-25">Hi-Fi Harmony</button>
              </form>

              <form action="/products" method="get">
                <button className="btn-25">Products</button>
              </form>

              <form action="/basket" method="get">
                <button className="btn-24">
                  Basket <Badge />
                </button>
              </form>
            </div>
          </nav>
        </header>

        <section>{children}</section>
        {/*         <footer>
          <CookieBanner />
        </footer> */}
      </body>
    </html>
  );
}
